### ISSUE TITLE
How to target styles for a specific vaadin-board?

### ISSUE THREAD

**Issue by samiheikki** [vaadin/vaadin-board#42]
I tried to specify `large`, `medium`, `small` classes for only 1 vaadin-board (code below). Is there a way to do this?

```
    <style>
      #first.large {
          font-size:20px;
      }
      #first.medium {
          font-size:16px;
      }
      #first.small {
          font-size:10px;
      }
    </style>
    <vaadin-board id="first">
      <vaadin-board-row>
        <div class="item">1</div>
        <div class="item">2</div>
        <div class="item">3</div>
        <div class="item">4</div>
      </vaadin-board-row>
      <vaadin-board-row>
        <div class="item">1</div>
        <div class="item">2</div>
      </vaadin-board-row>
    </vaadin-board>

    <vaadin-board id="second">
      <vaadin-board-row>
        <div class="item">1</div>
        <div class="item">2</div>
        <div class="item">3</div>
        <div class="item">4</div>
      </vaadin-board-row>
      <vaadin-board-row>
        <div class="item">1</div>
        <div class="item">2</div>
      </vaadin-board-row>
    </vaadin-board>
```

**Comment by Peppe** [comment]
The expected behaviour and actual behaviour would be nice to have listed here.

One note, ```large```,```medium``` and ```small``` is added to the ```<vaadin-board-row>``` level. So you should probably have a space there in your css to target the children of ```#first```.

```css
#first .large {
  font-size:20px;
}
```

**Comment by alvarezguille** [comment]
Exactly what @Peppe said, I'll try to clarify it in basic use docs.
Any suggestion on how it could be more clear?

**Comment by Peppe** [comment]
Note also that not all rows have the same sizing. This is due to element query (in contrast to media query). In nested rows, you end up in situations where you can ```large``` rows and ```small``` rows on the same screen.

For example in http://demo.vaadin.com/vbd/#/sales-dashboard on desktop sizes, the mid row has a big "Q1 product sales" graph that takes 75% of the row and then three smaller charts on the right within a nested row. The main row is in ```large``` mode,  but the nested row with the three smaller charts is in ```small``` mode as the space it is given is constricted.

**Comment by samiheikki** [comment]
Thanks for the support @alvarezguille and @Peppe. Everything fine imo, closing issue.
